export {
  UniversalConfidenceConflictAdaptiveFallbackEngine,
  createUniversalConfidenceConflictAdaptiveFallbackEngine,
  analyzeUniversalConfidenceConflictFallback,
  normalizeConfidenceConflictFallbackProfile,
  migrateConfidenceConflictFallbackProfile
} from './UniversalConfidenceConflictAdaptiveFallbackEngine.js';
