export {
  UniversalAssetDiscoveryMatchingResolutionEngine,
  createUniversalAssetDiscoveryMatchingResolutionEngine,
  analyzeUniversalAssetDiscoveryMatchingResolution,
  normalizeAssetDiscoveryMatchingResolutionProfile,
  migrateAssetDiscoveryMatchingResolutionProfile
} from './UniversalAssetDiscoveryMatchingResolutionEngine.js';
